<?php

/* for IDE autocomplete */
class XFCP_Akinak_CustomUserFieldSearch_ControllerPublic_Member extends XenForo_ControllerPublic_Member {}
class XFCP_Akinak_CustomUserFieldSearch_Model_User extends XenForo_Model_User {}
class XFCP_Akinak_CustomUserFieldSearch_ControllerPublic_Account extends XenForo_ControllerPublic_Account {}